// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------------ //
// edge_capture //
// ------------ //

#define edge_capture_wrap_target 0
#define edge_capture_wrap 12
#define edge_capture_pio_version 0

static __pio_const uint16_t edge_capture_program_instructions[] = {
            //     .wrap_target
    0xa02b, //  0: mov    x, ~null
    0x00c3, //  1: jmp    pin, 3
    0x0041, //  2: jmp    x--, 1
    0xa0c9, //  3: mov    isr, ~x
    0x4001, //  4: in     pins, 1
    0x8000, //  5: push   noblock
    0xa02b, //  6: mov    x, ~null
    0x00c9, //  7: jmp    pin, 9
    0x000a, //  8: jmp    10
    0x0047, //  9: jmp    x--, 7
    0xa0c9, // 10: mov    isr, ~x
    0x4001, // 11: in     pins, 1
    0x8000, // 12: push   noblock
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program edge_capture_program = {
    .instructions = edge_capture_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = edge_capture_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config edge_capture_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + edge_capture_wrap_target, offset + edge_capture_wrap);
    return c;
}

#include "hardware/clocks.h"
// pin: the comparator output (GP2 on this rig).
// f_pio_hz: PIO clock. 16 MHz gives 125 ns per count and keeps a 24 us bit at
// ~192 counts — small numbers, plenty of resolution, no risk of overflow.
static inline void edge_capture_init(PIO pio, uint sm, uint offset,
                                     uint pin, float f_pio_hz) {
    pio_sm_config c = edge_capture_program_get_default_config(offset);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);   // input
    sm_config_set_in_pins(&c, pin);      // for `in pins, 1`
    sm_config_set_jmp_pin(&c, pin);      // for `jmp pin`
    // Shift LEFT so `in pins,1` lands in the LSB, under the count.
    sm_config_set_in_shift(&c, false, false, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);            // 8 words deep
    sm_config_set_clkdiv(&c, (float)clock_get_hz(clk_sys) / f_pio_hz);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

