#!/usr/bin/env bash
#
# Grant non-root access to the debug probes this project uses.
#
# The symptom this fixes, on upload:
#     Error: libusb_open() failed with LIBUSB_ERROR_ACCESS
#
# Confusingly, the serial port usually works already (dialout covers it) and
# only the raw USB interface used for SWD/JTAG is blocked -- so it looks like a
# board fault rather than a permissions one.
#
#   ./setup-usb-permissions.sh            install rules (needs sudo)
#   ./setup-usb-permissions.sh --check    report only, no sudo, no changes
#
set -euo pipefail

RULES_FILE=/etc/udev/rules.d/99-ecu-probes.rules
CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

# vid:pid | description
PROBES=(
  "0483:374b|ST-LINK/V2.1 (Nucleo, Discovery)"
  "0483:3748|ST-LINK/V2"
  "0483:3754|ST-LINK/V3"
  "0483:374e|ST-LINK/V3 (no MSD)"
  "0483:374f|ST-LINK/V3 (dual)"
  "1a86:55d3|CH343 USB-UART (Waveshare ESP32 boards)"
  "1a86:7523|CH340 USB-UART"
  "10c4:ea60|CP2102 USB-UART"
  "0403:6001|FT232 USB-UART"
  "303a:1001|Espressif USB-Serial-JTAG"
  "16c0:0483|Teensy serial"
  "16c0:0478|Teensy HalfKay bootloader"
)

green() { printf '\033[32m%s\033[0m\n' "$1"; }
red()   { printf '\033[31m%s\033[0m\n' "$1"; }
dim()   { printf '\033[2m%s\033[0m\n' "$1"; }

echo "Debug probes currently attached"
echo "--------------------------------------------------------"
found_any=0
needs_fix=0
for entry in "${PROBES[@]}"; do
  vidpid="${entry%%|*}"; desc="${entry##*|}"
  line=$(lsusb 2>/dev/null | grep -i "$vidpid" || true)
  [[ -z "$line" ]] && continue
  found_any=1

  # Turn "Bus 001 Device 065:" into /dev/bus/usb/001/065 and check writability.
  node=$(sed -E 's|Bus ([0-9]+) Device ([0-9]+).*|/dev/bus/usb/\1/\2|' <<<"$line")
  if [[ -w "$node" ]]; then
    green "  OK    $desc"
    dim   "        $node"
  else
    red   "  BLOCKED  $desc"
    dim   "        $node -- $(stat -c '%A %U:%G' "$node" 2>/dev/null || echo '?')"
    needs_fix=1
  fi
done
[[ $found_any -eq 0 ]] && dim "  (none detected -- plug a board in)"
echo

if [[ $CHECK_ONLY -eq 1 ]]; then
  if [[ $needs_fix -eq 1 ]]; then
    echo "Run without --check to install the rules."
    exit 1
  fi
  green "Nothing to do."
  exit 0
fi

echo "Writing $RULES_FILE"
{
  echo "# ESP-ECU project: debug probe access for non-root users."
  echo "# Generated by tools/setup-usb-permissions.sh"
  for entry in "${PROBES[@]}"; do
    vidpid="${entry%%|*}"; desc="${entry##*|}"
    vid="${vidpid%%:*}"; pid="${vidpid##*:}"
    echo "# $desc"
    echo "SUBSYSTEM==\"usb\", ATTR{idVendor}==\"$vid\", ATTR{idProduct}==\"$pid\", MODE=\"0666\", TAG+=\"uaccess\""
  done
} | sudo tee "$RULES_FILE" >/dev/null

sudo udevadm control --reload-rules
sudo udevadm trigger
echo

# udev applies rules when a device is ADDED. Anything already enumerated keeps
# its old permissions, which is the most common reason this "does not work".
if [[ $needs_fix -eq 1 ]]; then
  red "Rules installed -- now UNPLUG AND REPLUG the board."
  echo
  echo "udev applies rules on device add, so an already-connected probe keeps"
  echo "its old permissions until it re-enumerates. Then verify with:"
  echo "    $0 --check"
else
  green "Rules installed. Nothing was blocked, so no replug needed."
fi
